### ISSUE TITLE
missing parameters in cice_in.nml

### ISSUE THREAD

**Issue by hakaseh** [COSIMA/1deg_jra55_iaf#9]
@pwongpan and I were looking at the CICE diagnostics, and noticed that at least six of them were absent in cice_in.nml. Four of these are set to 'm' by default (src/cice5/source/ice_history_shared.F90), and therefore they have been outputted in most of our runs, including OMIP2.

The missing parameters are: 

           f_alvdf     = 'x', f_alidf      = 'x', &
           f_alvdr_ai  = 'm', f_alidr_ai   = 'm', &
           f_alvdf_ai  = 'm', f_alidf_ai   = 'm', &

This issue appears to be present also in https://github.com/COSIMA/01deg_jra55_iaf/blob/master/ice/cice_in.nml, so fixing this should save up some disk space for diagnostics particularly in high-res runs.

**Comment by hakaseh** [comment]
@aekiss I'm revising this issue while developing `master+bgc` (e.g. https://github.com/COSIMA/1deg_jra55_iaf/tree/master+bgc). I identified there are seven diagnostics that are not defined in https://github.com/COSIMA/1deg_jra55_iaf/blob/master/ice/cice_in.nml, and because they are set to `'m'` by default, they are produced as output.

Should we define these and set to `'x'` in https://github.com/COSIMA/1deg_jra55_iaf/blob/master/ice/cice_in.nml? I can do for all 3 resolutions and do pull request from my fork repo. And can this change be made also to `master+bgc` by `git merge` (merging master to master+bgc)?

**Comment by hakaseh** [comment]
![Screen Shot 2021-11-10 at 10 36 27 am](https://user-images.githubusercontent.com/50728639/141029316-b04f4519-a429-4b09-9773-cb296260b8ce.png)

I should mention that these are the seven missing diagnostics (attached, except the first one ANGLET).

**Comment by aekiss** [comment]
Well spotted! Before we remove them we should see if anyone will miss them. Can you please check with Will and Petra and anyone else you can think of?

**Comment by aekiss** [comment]
As this is a more widespread problem I've made an access-om2 issue of it: https://github.com/COSIMA/access-om2/issues/250

I've also found a few more that aren't set.

**Comment by hakaseh** [comment]
sure, i can ask Will, Petra, and Pat. do you mean we should check if they need any of those for `cycle 4`?

i can see that at least `f_dagedtt` and `f_dagedtd` are missing in `ice/cice_in.nml` of e.g. https://github.com/COSIMA/1deg_jra55_iaf/tree/master, but my current experiment suggests (`/scratch/v45/hh0162/access-om2-cycle4/control/1deg_jra55_iamip2_his`) that they are set to `'x'`, because adding those seven diagnostics I noted above to `ice/cice_in.nml` results in producing no monthly output.

searching for "f_dagedtd" suggests that it is set to `'x'` in `cice5/source/ice_history.F90`:

```
grep --color -r "f_dagedtd" ~/scratch/access-om2-cycle4/src/cice5/source/
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history_shared.F90:           f_dagedtt   = 'm', f_dagedtd    = 'm', &
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history_shared.F90:           f_dagedtt,   f_dagedtd  , &
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history.F90:         f_dagedtd = 'x'
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history.F90:      call broadcast_scalar (f_dagedtd, master_task)
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history.F90:             ns1, f_dagedtd)
/home/581/hh0162/scratch/access-om2-cycle4/src/cice5/source/ice_history.F90:         if (f_dagedtd (1:1) /= 'x') &
```

**Comment by aekiss** [comment]
Thanks for asking around. 

Thanks for checking on `f_dagedtt` etc - I've responded [here](https://github.com/COSIMA/access-om2/issues/250#issuecomment-965829298).

I'll close this issue as I think we should continue discussion in https://github.com/COSIMA/access-om2/issues/250
